version: '3'
services:
  routerservice:
    build: "IntermediateRouting/."
    ports:
      - "8082:8082"
    networks: 
      - "mod-val-net"
  registryservice:
    build: "Convenio/."
    ports:
      - "8081:8081"
    networks: 
       - "mod-val-net"
networks:
  service-compose-net:
    driver: bridge

